language: ruby
rvm:
  - 2.1.5
env:
  - DB=postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - rake db:migrate RAILS_ENV=test --trace
  - rake db:test:prepare
  - rake
