# Do not keep production secrets in the repository,
# instead read values from the environment.
test:
  secret_key_base: a7b545c2ff96b9498458e0ff970dd73f481502e407dcb152822ff868c73cbaf905b1d9cd02679a8cdbaddf1d1dd9f7b6f40abd5aad1464ce2a6e5f5982de950a
  email_user_from: "admin@flashcards.com"

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_TOKEN"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  facebook_callback_url: <%= ENV["FACEBOOK_CALLBACK_URL"] %>
  email_user_from: <%= ENV["EMAIL_USER_FROM"] %>
  email_user_name: <%= ENV["EMAIL_USER_NAME"] %>
  email_user_password: <%= ENV["EMAIL_USER_PASSWORD"] %>
  email_address: "smtp.gmail.com"